PRIVATE_KEY_SOURCE      = '/home/douglas/.ssh/id_rsa.pub'
PRIVATE_KEY_DESTINATION = '/home/vagrant/.ssh/authorized_keys'
RSERVER_IP              = '10.238.4.110'
RSERVER_HOSTNAME        = 'SRV-DEV-RSERVER01-POA'
HADOOP_MASTER_IP        = '10.238.4.111'
HADOOP_MASTER_HOSTNAME  = 'SRV-DEV-HADOOP01-POA'
HADOOP_DATA01_IP        = '10.238.4.112'
HADOOP_DATA01_HOSTNAME  = 'SRV-DEV-HADOOP02-POA'
HADOOP_DATA02_IP        = '10.238.4.113'
HADOOP_DATA02_HOSTNAME  = 'SRV-DEV-HADOOP03-POA'
HADOOP_DATA03_IP        = '10.238.4.114'
HADOOP_DATA03_HOSTNAME  = 'SRV-DEV-HADOOP04-POA'

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  
  # define Master server
  config.vm.define RSERVER_HOSTNAME do |master|
    master.vm.hostname = RSERVER_HOSTNAME
    master.vm.box = "centos/7"
    master.vm.box_version = "1611.01"
    #master.vm.synced_folder ".", "/home/vagrant/src", mount_options: ["dmode=775,fmode=664"]
    master.vm.network "private_network", ip: RSERVER_IP
    master.vm.provider "virtualbox" do |v|
      v.name = RSERVER_HOSTNAME
      v.cpus = 2
      v.memory = 1024
    end
    # copy private key so hosts can ssh using key authentication (the script below sets permissions to 600)
    master.vm.provision :file do |file|
      file.source      = PRIVATE_KEY_SOURCE
      file.destination = PRIVATE_KEY_DESTINATION
    end
  end
end
