- name: Pull Rocker/RStudio image (https://hub.docker.com/r/rocker)
  docker_image:
    name: rocker/tidyverse
    pull: yes

- name: Creates a data container for RStudio server
  docker_container:
    name: rserver
    image: rocker/tidyverse
    hostname: rserver
    published_ports: 8787:8787
    restart_policy: always
    state: started
    volumes:
       - "/data:/home/rstudio/data"
    env:
       ROOT: true
       HTTP_PROXY: "{{ proxy_env.http_proxy }}"
       HTTPS_PROXY: "{{ proxy_env.http_proxy }}"

- name: Setup iptables do accept 8787 connections
  firewalld:
    port: 8787/tcp
    permanent: true
    state: enabled

- name: Ensure depdencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libjpeg-dev
    - libtiff5-dev
    - libgmp-dev
    - default-jdk
    - r-base-dev
