- name: Configure rserver
  hosts: rserver
  become: yes
  
  roles:
    - epel
    - pip
    - docker
    - rserver

  environment:
    http_proxy: "{{ proxy_env.http_proxy }}"
    https_proxy: "{{ proxy_env.https_proxy }}" 
