- name: Pull postgresql image (https://hub.docker.com/_/postgres)
  docker_image:
    name: postgres
    pull: yes

- name: Creates container for postgresql
  docker_container:
    name: postgresql
    image: postgres
    hostname: DEV-USGZH-POSTGRESQL01-POA
    restart_policy: always
    state: started
    env:
       POSTGRES_PASSWORD=postgres
